### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by devinchristianson** [devinchristianson/daj#47]
- [x] Add MIDI support - Alex Revello
- [ ] Build out basic Flask App - Devin
- [x] Chord switching - Alex Feren

**Comment by devinchristianson** [comment]
Added Flask app
Added prod docker container.
Still need to improve CI pipeline for prod

**Comment by devinchristianson** [comment]
Added auto-deploy on release for prod docker container to DockerHub

**Comment by AlexandreFeren** [comment]
Sprint 3 over, closing this issue and moving the "build out basic flask app" note to sprint 4
