### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by AlexandreFeren** [devinchristianson/daj#72]
- [x] Build out basic Flask App (Devin) - Carried over from Sprint 3
- [ ] Touch screen support
- [ ] User accounts
- [ ] Playback implementation
- [ ] Functionality to save chords/progressions
- [ ] Functionality to upload chords/progressions
- [ ] Refactor code for consistency

**Comment by devinchristianson** [comment]
Sprint backlog for this sprint is done.
